export const CONTACTO = [
    {
        nombre: 'Pere Alemany Tomàs',
        tooltip: 'Pere',
        cargo: 'Coordinador General',
        // email: 'p_alemanyt@a.iescalvia.com',
        email: 'voley_tournament@iescalvia.com',
        descripcion: 'En Pere és un dels encarregats de la planificació general del torneig, assegurant que tot funcioni de manera fluida. És el principal responsable de la logística i la coordinació amb els equips participants.',
    },
    {
        nombre: 'Miguel Socias Perez',
        tooltip: 'Miguel',
        cargo: 'Relacions Públiques',
        // email: 'm_sociasp@a.iescalvia.com',
        email: 'voley_tournament@iescalvia.com',
        descripcion: 'En Miguel és l’encarregat de les Relacions Públiques del torneig. La seva funció principal és mantenir la comunicació amb els mitjans, voluntaris i participants, a més de representar el torneig davant d’altres entitats. També s’ocupa de transmetre una imatge positiva de l’esdeveniment i de reforçar els vincles amb la comunitat.',
    },
    {
        nombre: 'Lucas Hechavarria Escartin',
        tooltip: 'Lucas',
        cargo: 'Responsable de Inscripcions',
        // email: 'l_hechavarriae@a.iescalvia.com',
        email: 'voley_tournament@iescalvia.com',
        descripcion: 'En Lucas gestiona totes les inscripcions dels equips. Si tens dubtes sobre el registre o el procés de participació, ell és la persona adequada.',
    },
    {
        nombre: 'Santino Bonavera',
        tooltip: 'Santino',
        cargo: 'Responsable de Voluntaris',
        // email: 's_bonavera@a.iescalvia.com',
        email: 'voley_tournament@iescalvia.com',
        descripcion: 'En Santi coordina els voluntaris que ajuda en el desenvolupament del torneig. Si estàs interessat a col·laborar o tens preguntes sobre les funcions dels voluntaris, pots parlar amb ell.',
    },
    {
        nombre: 'Luca Emanuel Lopez',
        tooltip: 'Luca',
        cargo: 'Responsable Àrbitres i Normatives',
        // email: 'le_lopez@a.iescalvia.com',
        email: 'voley_tournament@iescalvia.com',
        descripcion: 'En Luca es el encarrega de les assignaciós dels àrbitres i del compliment de les normatives del torneig. Qualsevol consulta sobre regles o arbitratge ha de dirigir-se a ell.',
    },
    {
        nombre: 'Juan Jose Gonzalez',
        tooltip: 'Juanjo',
        cargo: 'Encargat de Material i Equips',
        // email: 'jgonzalez@iescalvia.com',
        email: 'voley_tournament@iescalvia.com',
        descripcion: 'En Juanjo és responsable de assegurar-se que tot el material necessari estigui a punt. Des de les xarxes fins a les pilotes, ell s\'assegura que els partits es juguin sense problemes.',
    },
    {
        nombre: 'Ricardo Figuerola Lozano',
        tooltip: 'Ricardo',
        cargo: 'Professor Responsable',
        // email: 'jgonzalez@iescalvia.com',
        email: 'voley_tournament@iescalvia.com',
        descripcion: 'El professor responsable fa d’enllaç entre l’organització i el centre educatiu. S’encarrega de supervisar totes les àrees implicades, assegurant que l’esdeveniment respecti els valors educatius i esportius. A més, dona suport a l’equip organitzador i garanteix que el torneig compti amb l’aprovació i el seguiment institucional.',
    },
    {
        nombre: 'Ruben Esteve Maurell',
        tooltip: 'Ruben',
        cargo: 'Professor Responsable',
        // email: 'jgonzalez@iescalvia.com',
        email: 'voley_tournament@iescalvia.com',
        descripcion: 'El professor responsable fa d’enllaç entre l’organització i el centre educatiu. S’encarrega de supervisar totes les àrees implicades, assegurant que l’esdeveniment respecti els valors educatius i esportius. A més, dona suport a l’equip organitzador i garanteix que el torneig compti amb l’aprovació i el seguiment institucional.',
    },
    
    {
        nombre: 'Pere Alemany Tomàs',
        tooltip: 'Pere',
        cargo: 'Desenvolupador Web',
        // email: 'jgonzalez@iescalvia.com',
        email: 'voley_tournament@iescalvia.com',
        descripcion: `En Pere és l'encarregat del desenvolupament i manteniment de la web del torneig, assegurant que tota la informació estigui disponible i actualitzada. És responsable de la implementació de noves funcionalitats, la resolució de problemes tècnics i l'optimització del lloc per oferir una experiència fluida als usuaris.`,
    },
    {
        nombre: 'Estefania Escamilla Garcia',
        tooltip: 'Estefania',
        cargo: 'Responsable de la Playlist',
        // email: 'jgonzalez@iescalvia.com',
        email: 'voley_tournament@iescalvia.com',
        descripcion: `Na Estefania és l'encarregada de seleccionar i gestionar la playlist oficial del torneig, creant l’ambient perfecte perquè jugadors i espectadors gaudeixin de l’experiència. S’assegura que la música motivi els equips abans, durant i després dels partits, adaptant la selecció de cançons segons el moment de la competició. Si tens alguna suggerència musical, pots contactar amb ella!`,
    },
    {
        nombre: 'Miquel Sureda Rossello',
        tooltip: 'Miquel',
        cargo: 'Responsable de Fotografia',
        // email: 'jgonzalez@iescalvia.com',
        email: 'voley_tournament@iescalvia.com',
        descripcion: `En Miquel s'encarrega d'immortalitzar els millors moments del torneig. Des de les jugades més espectaculars fins a l'ambient a les grades, captura cada detall perquè els participants tinguin records visuals de l'esdeveniment.`,
    },
    {
        nombre: 'Marina Piña Muñoz',
        tooltip: 'Marina',
        cargo: `Responsable d'Oficials de Taula`,
        // email: 'jgonzalez@iescalvia.com',
        email: 'voley_tournament@iescalvia.com',
        descripcion: `Na Marina és l’encarregada de portar el control oficial dels partits des de la taula d’anotació. Registra els punts, controla el temps de joc i assegura que totes les incidències siguin anotades correctament en l’acta del partit. També col·labora amb els àrbitres per garantir que les normatives es compleixin i que els resultats siguin registrats de manera precisa.`,
    }
];
